### ISSUE TITLE
Collaborators on People section

### ISSUE THREAD

**Issue by TomMaullin** [NISOx-BDI/NISOx-BDI.github.io#18]
Currently the 'people' page on the website is missing collaborators. This can be rectified by updated the `people.yml` file found in _data. I believe @nicholst you said you would have to do this a long time ago in email.

**Comment by nicholst** [comment]
Tom,

Please enter the following for a “WIP” so we can ‘merge’ and move ahead.  If you can google an obvious link for each person great, otherwise don’t worry about it.


* Stephen Smith, University of Oxford
* Timothy Johnson, University of Michigan
* Tor Wager, University of Colorado
* Tal Yarkoni, University of Texas Austin
* Armin Schwartzman, University of California San Diego
* Camille Maumet, Rennes

**Comment by TomMaullin** [comment]
Hi @nicholst,

Would you like these people to have pictures also or just short entries like the alumni?

**Comment by TomMaullin** [comment]
I have added these people to the website and merged my changes with the master branch on this repository. Please let me know if this is okay!
