### ISSUE TITLE
Pubs: References don't list journal ("venue") pages

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/NISOx-BDI.github.io#2]
Many entires are lacking the volume and number entry, and none seem to have any page numbers.  This is frustrating.

Need to see how many more things are missing/messed up and decide to (a) fix or (b) go with another system.

**Comment by cmaumet** [comment]
Just as a note: if `bibble` ends up not being flexible enough we could consider https://github.com/inukshuk/jekyll-scholar.

**Comment by TomMaullin** [comment]
As far as I can see... those entries that are missing volume and number entry are missing are missing them because they don't have any stored in `pubs.bib`. Do you have any examples of publications with volume numbers stored in `pubs.bib` whose volume numbers do not appear on the website?

However, currently page numbers are indeed not accounted for in the code. This is something I am now fixing.

**Comment by TomMaullin** [comment]
This has been addressed in PR #15
